server:
  port: 8080

spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      # 数据库 1
      db1:
        url: jdbc:postgresql://192.168.1.177:5432/paper1
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      # 数据库 2
      db2:
        url: jdbc:h2:~/test_code;AUTO_SERVER=TRUE
        username: sa
        password:
        driver-class-name: org.h2.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        hibernate.database-platform: org.hibernate.dialect.H2Dialect





